---
# tasks file for common
- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Remove old Kubernetes repo
  file:
    path: /etc/apt/sources.list.d/kubernetes.list
    state: absent

- name: Remove swap from fstab
  replace:
    path: /etc/fstab
    regexp: '^([^#].*swap.*)$'
    replace: '# \1'

- name: Load kernel modules
  copy:
    dest: /etc/modules-load.d/k8s.conf
    content: |
      overlay
      br_netfilter

- name: Load modules
  shell: |
    modprobe overlay
    modprobe br_netfilter

- name: Sysctl params
  copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-iptables = 1
      net.ipv4.ip_forward = 1
      net.bridge.bridge-nf-call-ip6tables = 1

- name: Apply sysctl
  command: sysctl --system

- import_tasks: containerd.yml

- import_tasks: kubernetes.yml
