---
- name: Prepare all nodes
  hosts: kube_cluster
  become: true
  roles:
    - common

- name: Init Kubernetes master
  hosts: kube_master
  become: true
  roles:
    - kube-master
    - kube-network

- name: Join workers to cluster
  hosts: kube_workers
  become: true
  roles:
    - kube-worker
